import type { Order } from '@/lib/types'

export const orders: Order[] = [
  {
    id: 'ORD-2024-001',
    kanaal: 'WooCommerce',
    kanaalOrderId: 'WC-10042',
    status: 'new',
    afasStatus: 'not_entered',
    klantNaam: 'Sophie van den Berg',
    klantEmail: 'sophie.vdberg@example.nl',
    klantAdres: 'Keizersgracht 112',
    klantPostcode: '1015 CW',
    klantStad: 'Amsterdam',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-BLK-M', naam: 'Chill-Dept Hoodie Zwart M', aantal: 1, prijs: 79.95 },
      { sku: 'CD-SHIRT-WHT-L', naam: 'Chill-Dept T-shirt Wit L', aantal: 2, prijs: 34.95 },
    ],
    totaal: 149.85,
    aangemaaktOp: '2024-06-04T08:12:00Z',
    bijgewerktOp: '2024-06-04T08:12:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-002',
    kanaal: 'bol.com',
    kanaalOrderId: 'BOL-8871234',
    status: 'processing',
    afasStatus: 'entered',
    klantNaam: 'Lars Jansen',
    klantEmail: 'lars.jansen@example.nl',
    klantAdres: 'Lange Leidsedwarsstraat 55',
    klantPostcode: '1017 ND',
    klantStad: 'Amsterdam',
    klantLand: 'NL',
    regels: [{ sku: 'CD-JOGGER-GRY-L', naam: 'Chill-Dept Jogger Grijs L', aantal: 1, prijs: 64.95 }],
    totaal: 64.95,
    aangemaaktOp: '2024-06-04T09:03:00Z',
    bijgewerktOp: '2024-06-04T10:45:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T10:45:00Z',
  },
  {
    id: 'ORD-2024-003',
    kanaal: 'Mirakl',
    kanaalOrderId: 'MRK-55002',
    status: 'ready_to_ship',
    afasStatus: 'entered',
    klantNaam: 'Emma de Vries',
    klantEmail: 'emma.devries@example.nl',
    klantAdres: 'Nieuwe Binnenweg 87',
    klantPostcode: '3014 GC',
    klantStad: 'Rotterdam',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-CAP-BLK', naam: 'Chill-Dept Cap Zwart', aantal: 1, prijs: 29.95 },
      { sku: 'CD-HOODIE-NVY-S', naam: 'Chill-Dept Hoodie Navy S', aantal: 1, prijs: 79.95 },
    ],
    totaal: 109.90,
    aangemaaktOp: '2024-06-03T14:22:00Z',
    bijgewerktOp: '2024-06-04T07:30:00Z',
    notities: 'Klant heeft gevraagd om cadeauverpakking',
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T07:35:00Z',
  },
  {
    id: 'ORD-2024-004',
    kanaal: 'eBay',
    kanaalOrderId: 'EB-29918273',
    status: 'shipped',
    afasStatus: 'entered',
    klantNaam: 'Tom Bakker',
    klantEmail: 'tom.bakker@example.nl',
    klantAdres: 'Mariaplaats 14',
    klantPostcode: '3511 LL',
    klantStad: 'Utrecht',
    klantLand: 'NL',
    regels: [{ sku: 'CD-SHIRT-BLK-M', naam: 'Chill-Dept T-shirt Zwart M', aantal: 3, prijs: 34.95 }],
    totaal: 104.85,
    aangemaaktOp: '2024-06-02T11:00:00Z',
    bijgewerktOp: '2024-06-03T09:15:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-02T14:00:00Z',
  },
  {
    id: 'ORD-2024-005',
    kanaal: 'WooCommerce',
    kanaalOrderId: 'WC-10043',
    status: 'completed',
    afasStatus: 'entered',
    klantNaam: 'Nina Smits',
    klantEmail: 'nina.smits@example.nl',
    klantAdres: 'Dorpsstraat 3',
    klantPostcode: '5258 HL',
    klantStad: 'Berlicum',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-BLK-L', naam: 'Chill-Dept Hoodie Zwart L', aantal: 1, prijs: 79.95 },
      { sku: 'CD-CAP-WHT', naam: 'Chill-Dept Cap Wit', aantal: 2, prijs: 29.95 },
    ],
    totaal: 139.85,
    aangemaaktOp: '2024-05-30T16:40:00Z',
    bijgewerktOp: '2024-06-02T14:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-05-31T09:00:00Z',
  },
  {
    id: 'ORD-2024-006',
    kanaal: 'bol.com',
    kanaalOrderId: 'BOL-8871599',
    status: 'cancelled',
    afasStatus: 'not_entered',
    klantNaam: 'Kevin Mulder',
    klantEmail: 'kevin.mulder@example.nl',
    klantAdres: 'Koningsweg 18',
    klantPostcode: '6833 JA',
    klantStad: 'Arnhem',
    klantLand: 'NL',
    regels: [{ sku: 'CD-JOGGER-BLK-M', naam: 'Chill-Dept Jogger Zwart M', aantal: 1, prijs: 64.95 }],
    totaal: 64.95,
    aangemaaktOp: '2024-06-01T10:00:00Z',
    bijgewerktOp: '2024-06-01T12:30:00Z',
    notities: 'Geannuleerd op verzoek van klant',
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-007',
    kanaal: 'Mirakl',
    kanaalOrderId: 'MRK-55103',
    status: 'returned',
    afasStatus: 'not_entered',
    klantNaam: 'Femke Visser',
    klantEmail: 'femke.visser@example.nl',
    klantAdres: 'Vondellaan 22',
    klantPostcode: '2332 AA',
    klantStad: 'Leiden',
    klantLand: 'NL',
    regels: [{ sku: 'CD-SHIRT-WHT-S', naam: 'Chill-Dept T-shirt Wit S', aantal: 1, prijs: 34.95 }],
    totaal: 34.95,
    aangemaaktOp: '2024-05-28T09:00:00Z',
    bijgewerktOp: '2024-06-03T11:20:00Z',
    notities: 'Maat te groot — retour ontvangen',
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-008',
    kanaal: 'eBay',
    kanaalOrderId: 'EB-29918300',
    status: 'failed',
    afasStatus: 'not_entered',
    klantNaam: 'Daan Peters',
    klantEmail: 'daan.peters@example.nl',
    klantAdres: 'Zuiddijk 9',
    klantPostcode: '1505 HE',
    klantStad: 'Zaandam',
    klantLand: 'NL',
    regels: [{ sku: 'CD-HOODIE-NVY-M', naam: 'Chill-Dept Hoodie Navy M', aantal: 1, prijs: 79.95 }],
    totaal: 79.95,
    aangemaaktOp: '2024-06-04T06:55:00Z',
    bijgewerktOp: '2024-06-04T07:05:00Z',
    notities: 'Betaling mislukt — order geblokkeerd',
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-009',
    kanaal: 'WooCommerce',
    kanaalOrderId: 'WC-10044',
    status: 'processing',
    afasStatus: 'entered',
    klantNaam: 'Iris van Leeuwen',
    klantEmail: 'iris.vleeuwen@example.nl',
    klantAdres: 'Havenstraat 44',
    klantPostcode: '9711 PB',
    klantStad: 'Groningen',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-CAP-BLK', naam: 'Chill-Dept Cap Zwart', aantal: 2, prijs: 29.95 },
      { sku: 'CD-SHIRT-BLK-L', naam: 'Chill-Dept T-shirt Zwart L', aantal: 1, prijs: 34.95 },
    ],
    totaal: 94.85,
    aangemaaktOp: '2024-06-04T07:30:00Z',
    bijgewerktOp: '2024-06-04T09:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T09:00:00Z',
  },
  {
    id: 'ORD-2024-010',
    kanaal: 'bol.com',
    kanaalOrderId: 'BOL-8872100',
    status: 'shipped',
    afasStatus: 'entered',
    klantNaam: 'Mark Hendriks',
    klantEmail: 'mark.hendriks@example.nl',
    klantAdres: 'Wilhelminastraat 66',
    klantPostcode: '5611 HK',
    klantStad: 'Eindhoven',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-JOGGER-GRY-M', naam: 'Chill-Dept Jogger Grijs M', aantal: 1, prijs: 64.95 },
      { sku: 'CD-HOODIE-BLK-M', naam: 'Chill-Dept Hoodie Zwart M', aantal: 1, prijs: 79.95 },
    ],
    totaal: 144.90,
    aangemaaktOp: '2024-06-02T15:10:00Z',
    bijgewerktOp: '2024-06-03T10:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-02T17:30:00Z',
  },
  {
    id: 'ORD-2024-011',
    kanaal: 'Mirakl',
    kanaalOrderId: 'MRK-55210',
    status: 'new',
    afasStatus: 'not_entered',
    klantNaam: 'Anouk Brouwer',
    klantEmail: 'anouk.brouwer@example.nl',
    klantAdres: 'Bosweg 7',
    klantPostcode: '7327 AC',
    klantStad: 'Apeldoorn',
    klantLand: 'NL',
    regels: [{ sku: 'CD-SHIRT-WHT-M', naam: 'Chill-Dept T-shirt Wit M', aantal: 4, prijs: 34.95 }],
    totaal: 139.80,
    aangemaaktOp: '2024-06-04T10:00:00Z',
    bijgewerktOp: '2024-06-04T10:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-012',
    kanaal: 'eBay',
    kanaalOrderId: 'EB-29918401',
    status: 'ready_to_ship',
    afasStatus: 'entered',
    klantNaam: 'Pieter de Graaf',
    klantEmail: 'pieter.degraaf@example.nl',
    klantAdres: 'Stationsplein 1',
    klantPostcode: '2515 BW',
    klantStad: 'Den Haag',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-BLK-XL', naam: 'Chill-Dept Hoodie Zwart XL', aantal: 1, prijs: 79.95 },
      { sku: 'CD-JOGGER-BLK-XL', naam: 'Chill-Dept Jogger Zwart XL', aantal: 1, prijs: 64.95 },
    ],
    totaal: 144.90,
    aangemaaktOp: '2024-06-03T08:30:00Z',
    bijgewerktOp: '2024-06-04T08:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T08:00:00Z',
  },
  {
    id: 'ORD-2024-013',
    kanaal: 'WooCommerce',
    kanaalOrderId: 'WC-10045',
    status: 'completed',
    afasStatus: 'entered',
    klantNaam: 'Chantal Wolff',
    klantEmail: 'chantal.wolff@example.nl',
    klantAdres: 'Prinsengracht 482',
    klantPostcode: '1017 KH',
    klantStad: 'Amsterdam',
    klantLand: 'NL',
    regels: [{ sku: 'CD-CAP-BLK', naam: 'Chill-Dept Cap Zwart', aantal: 3, prijs: 29.95 }],
    totaal: 89.85,
    aangemaaktOp: '2024-05-29T12:00:00Z',
    bijgewerktOp: '2024-06-01T09:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-05-29T14:00:00Z',
  },
  {
    id: 'ORD-2024-014',
    kanaal: 'bol.com',
    kanaalOrderId: 'BOL-8872345',
    status: 'processing',
    afasStatus: 'not_entered',
    klantNaam: 'Joris Timmermans',
    klantEmail: 'joris.timmermans@example.nl',
    klantAdres: 'Middenlaan 33',
    klantPostcode: '2012 HX',
    klantStad: 'Haarlem',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-NVY-L', naam: 'Chill-Dept Hoodie Navy L', aantal: 1, prijs: 79.95 },
      { sku: 'CD-SHIRT-WHT-L', naam: 'Chill-Dept T-shirt Wit L', aantal: 1, prijs: 34.95 },
    ],
    totaal: 114.90,
    aangemaaktOp: '2024-06-04T06:00:00Z',
    bijgewerktOp: '2024-06-04T09:30:00Z',
    notities: 'Adres verificatie vereist',
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-015',
    kanaal: 'Mirakl',
    kanaalOrderId: 'MRK-55315',
    status: 'shipped',
    afasStatus: 'entered',
    klantNaam: 'Roos van Dijk',
    klantEmail: 'roos.vandijk@example.nl',
    klantAdres: 'Herenweg 14',
    klantPostcode: '2105 MG',
    klantStad: 'Heemstede',
    klantLand: 'NL',
    regels: [{ sku: 'CD-JOGGER-GRY-S', naam: 'Chill-Dept Jogger Grijs S', aantal: 2, prijs: 64.95 }],
    totaal: 129.90,
    aangemaaktOp: '2024-06-02T13:00:00Z',
    bijgewerktOp: '2024-06-03T08:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-02T16:00:00Z',
  },
  {
    id: 'ORD-2024-016',
    kanaal: 'eBay',
    kanaalOrderId: 'EB-29918500',
    status: 'new',
    afasStatus: 'not_entered',
    klantNaam: 'Sander Kuijpers',
    klantEmail: 'sander.kuijpers@example.nl',
    klantAdres: 'Alexanderstraat 9',
    klantPostcode: '3116 WC',
    klantStad: 'Schiedam',
    klantLand: 'NL',
    regels: [{ sku: 'CD-SHIRT-BLK-XL', naam: 'Chill-Dept T-shirt Zwart XL', aantal: 1, prijs: 34.95 }],
    totaal: 34.95,
    aangemaaktOp: '2024-06-04T10:45:00Z',
    bijgewerktOp: '2024-06-04T10:45:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-017',
    kanaal: 'WooCommerce',
    kanaalOrderId: 'WC-10046',
    status: 'returned',
    afasStatus: 'not_entered',
    klantNaam: 'Lotte Meijer',
    klantEmail: 'lotte.meijer@example.nl',
    klantAdres: 'Nassaukade 77',
    klantPostcode: '1052 EC',
    klantStad: 'Amsterdam',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-BLK-S', naam: 'Chill-Dept Hoodie Zwart S', aantal: 1, prijs: 79.95 },
    ],
    totaal: 79.95,
    aangemaaktOp: '2024-05-27T14:00:00Z',
    bijgewerktOp: '2024-06-03T15:00:00Z',
    notities: 'Beschadigd ontvangen — retour in behandeling',
    trackingCode: null,
    klantTelefoon: null,
  },
  {
    id: 'ORD-2024-018',
    kanaal: 'bol.com',
    kanaalOrderId: 'BOL-8872600',
    status: 'ready_to_ship',
    afasStatus: 'entered',
    klantNaam: 'Bas Vermeer',
    klantEmail: 'bas.vermeer@example.nl',
    klantAdres: 'Parkweg 50',
    klantPostcode: '4818 SC',
    klantStad: 'Breda',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-CAP-WHT', naam: 'Chill-Dept Cap Wit', aantal: 1, prijs: 29.95 },
      { sku: 'CD-SHIRT-WHT-XL', naam: 'Chill-Dept T-shirt Wit XL', aantal: 2, prijs: 34.95 },
    ],
    totaal: 99.85,
    aangemaaktOp: '2024-06-03T11:00:00Z',
    bijgewerktOp: '2024-06-04T06:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T06:00:00Z',
  },
  {
    id: 'ORD-2024-019',
    kanaal: 'Mirakl',
    kanaalOrderId: 'MRK-55400',
    status: 'completed',
    afasStatus: 'entered',
    klantNaam: 'Hanna Bosman',
    klantEmail: 'hanna.bosman@example.nl',
    klantAdres: 'Schoolstraat 5',
    klantPostcode: '6411 JC',
    klantStad: 'Heerlen',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-JOGGER-BLK-S', naam: 'Chill-Dept Jogger Zwart S', aantal: 1, prijs: 64.95 },
      { sku: 'CD-CAP-BLK', naam: 'Chill-Dept Cap Zwart', aantal: 1, prijs: 29.95 },
    ],
    totaal: 94.90,
    aangemaaktOp: '2024-05-31T09:00:00Z',
    bijgewerktOp: '2024-06-02T16:00:00Z',
    notities: null,
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-05-31T11:00:00Z',
  },
  {
    id: 'ORD-2024-020',
    kanaal: 'eBay',
    kanaalOrderId: 'EB-29918600',
    status: 'processing',
    afasStatus: 'entered',
    klantNaam: 'Thijs van der Berg',
    klantEmail: 'thijs.vdberg@example.nl',
    klantAdres: 'Rijksweg 101',
    klantPostcode: '6199 AC',
    klantStad: 'Maastricht',
    klantLand: 'NL',
    regels: [
      { sku: 'CD-HOODIE-NVY-XL', naam: 'Chill-Dept Hoodie Navy XL', aantal: 1, prijs: 79.95 },
      { sku: 'CD-JOGGER-GRY-XL', naam: 'Chill-Dept Jogger Grijs XL', aantal: 1, prijs: 64.95 },
      { sku: 'CD-SHIRT-BLK-XL', naam: 'Chill-Dept T-shirt Zwart XL', aantal: 2, prijs: 34.95 },
    ],
    totaal: 214.80,
    aangemaaktOp: '2024-06-04T05:00:00Z',
    bijgewerktOp: '2024-06-04T08:30:00Z',
    notities: 'Grote bestelling — prioriteit',
    trackingCode: null,
    klantTelefoon: null,
    afasIngevoerdOp: '2024-06-04T08:30:00Z',
  },
]
