import type { Product } from '@/lib/types'

export const products: Product[] = [
  {
    id: 'PROD-001',
    sku: 'CD-HOODIE-BLK-S',
    naam: 'Chill-Dept Hoodie Zwart S',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.65,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl'],
  },
  {
    id: 'PROD-002',
    sku: 'CD-HOODIE-BLK-M',
    naam: 'Chill-Dept Hoodie Zwart M',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.68,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-003',
    sku: 'CD-HOODIE-BLK-L',
    naam: 'Chill-Dept Hoodie Zwart L',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.72,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-004',
    sku: 'CD-HOODIE-BLK-XL',
    naam: 'Chill-Dept Hoodie Zwart XL',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.76,
    actief: true,
    kanalen: ['WooCommerce', 'eBay'],
  },
  {
    id: 'PROD-005',
    sku: 'CD-HOODIE-NVY-S',
    naam: 'Chill-Dept Hoodie Navy S',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.65,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com'],
  },
  {
    id: 'PROD-006',
    sku: 'CD-HOODIE-NVY-M',
    naam: 'Chill-Dept Hoodie Navy M',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.68,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'eBay'],
  },
  {
    id: 'PROD-007',
    sku: 'CD-HOODIE-NVY-L',
    naam: 'Chill-Dept Hoodie Navy L',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.72,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl'],
  },
  {
    id: 'PROD-008',
    sku: 'CD-HOODIE-NVY-XL',
    naam: 'Chill-Dept Hoodie Navy XL',
    categorie: 'Hoodies',
    inkoopprijs: 28.00,
    verkoopprijs: 79.95,
    gewicht: 0.76,
    actief: true,
    kanalen: ['WooCommerce', 'eBay'],
  },
  {
    id: 'PROD-009',
    sku: 'CD-SHIRT-BLK-M',
    naam: 'Chill-Dept T-shirt Zwart M',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.22,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'eBay'],
  },
  {
    id: 'PROD-010',
    sku: 'CD-SHIRT-BLK-L',
    naam: 'Chill-Dept T-shirt Zwart L',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.24,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-011',
    sku: 'CD-SHIRT-BLK-XL',
    naam: 'Chill-Dept T-shirt Zwart XL',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.26,
    actief: true,
    kanalen: ['WooCommerce', 'eBay'],
  },
  {
    id: 'PROD-012',
    sku: 'CD-SHIRT-WHT-S',
    naam: 'Chill-Dept T-shirt Wit S',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.22,
    actief: true,
    kanalen: ['WooCommerce', 'Mirakl'],
  },
  {
    id: 'PROD-013',
    sku: 'CD-SHIRT-WHT-M',
    naam: 'Chill-Dept T-shirt Wit M',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.22,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl'],
  },
  {
    id: 'PROD-014',
    sku: 'CD-SHIRT-WHT-L',
    naam: 'Chill-Dept T-shirt Wit L',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.24,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-015',
    sku: 'CD-SHIRT-WHT-XL',
    naam: 'Chill-Dept T-shirt Wit XL',
    categorie: 'T-shirts',
    inkoopprijs: 12.00,
    verkoopprijs: 34.95,
    gewicht: 0.26,
    actief: false,
    kanalen: ['WooCommerce'],
  },
  {
    id: 'PROD-016',
    sku: 'CD-JOGGER-BLK-S',
    naam: 'Chill-Dept Jogger Zwart S',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.45,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl'],
  },
  {
    id: 'PROD-017',
    sku: 'CD-JOGGER-BLK-M',
    naam: 'Chill-Dept Jogger Zwart M',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.47,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-018',
    sku: 'CD-JOGGER-BLK-XL',
    naam: 'Chill-Dept Jogger Zwart XL',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.50,
    actief: true,
    kanalen: ['WooCommerce', 'eBay'],
  },
  {
    id: 'PROD-019',
    sku: 'CD-JOGGER-GRY-S',
    naam: 'Chill-Dept Jogger Grijs S',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.45,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl'],
  },
  {
    id: 'PROD-020',
    sku: 'CD-JOGGER-GRY-M',
    naam: 'Chill-Dept Jogger Grijs M',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.47,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com'],
  },
  {
    id: 'PROD-021',
    sku: 'CD-JOGGER-GRY-L',
    naam: 'Chill-Dept Jogger Grijs L',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.49,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'eBay'],
  },
  {
    id: 'PROD-022',
    sku: 'CD-JOGGER-GRY-XL',
    naam: 'Chill-Dept Jogger Grijs XL',
    categorie: 'Joggers',
    inkoopprijs: 22.00,
    verkoopprijs: 64.95,
    gewicht: 0.50,
    actief: true,
    kanalen: ['WooCommerce', 'eBay'],
  },
  {
    id: 'PROD-023',
    sku: 'CD-CAP-BLK',
    naam: 'Chill-Dept Cap Zwart',
    categorie: 'Accessoires',
    inkoopprijs: 9.00,
    verkoopprijs: 29.95,
    gewicht: 0.18,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com', 'Mirakl', 'eBay'],
  },
  {
    id: 'PROD-024',
    sku: 'CD-CAP-WHT',
    naam: 'Chill-Dept Cap Wit',
    categorie: 'Accessoires',
    inkoopprijs: 9.00,
    verkoopprijs: 29.95,
    gewicht: 0.18,
    actief: true,
    kanalen: ['WooCommerce', 'bol.com'],
  },
]
