import type { SyncLog } from '@/lib/types'

export const syncLogs: SyncLog[] = [
  {
    id: 'SYNC-001',
    kanaal: 'WooCommerce',
    type: 'orders',
    status: 'success',
    aantalVerwerkt: 8,
    aantalFouten: 0,
    bericht: 'Alle orders succesvol gesynchroniseerd',
    uitgevoerdOp: '2024-06-04T10:00:00Z',
  },
  {
    id: 'SYNC-002',
    kanaal: 'bol.com',
    type: 'orders',
    status: 'success',
    aantalVerwerkt: 5,
    aantalFouten: 0,
    bericht: 'Alle orders succesvol gesynchroniseerd',
    uitgevoerdOp: '2024-06-04T10:01:00Z',
  },
  {
    id: 'SYNC-003',
    kanaal: 'Mirakl',
    type: 'orders',
    status: 'warning',
    aantalVerwerkt: 4,
    aantalFouten: 1,
    bericht: '1 order kon niet worden geladen: ongeldige orderstatus',
    uitgevoerdOp: '2024-06-04T10:02:00Z',
  },
  {
    id: 'SYNC-004',
    kanaal: 'eBay',
    type: 'orders',
    status: 'error',
    aantalVerwerkt: 0,
    aantalFouten: 3,
    bericht: 'API-verbinding mislukt: authenticatiefout (401)',
    uitgevoerdOp: '2024-06-04T10:03:00Z',
  },
  {
    id: 'SYNC-005',
    kanaal: 'WooCommerce',
    type: 'voorraad',
    status: 'success',
    aantalVerwerkt: 24,
    aantalFouten: 0,
    bericht: 'Voorraadniveaus bijgewerkt voor 24 SKUs',
    uitgevoerdOp: '2024-06-04T09:30:00Z',
  },
  {
    id: 'SYNC-006',
    kanaal: 'bol.com',
    type: 'voorraad',
    status: 'success',
    aantalVerwerkt: 18,
    aantalFouten: 0,
    bericht: 'Voorraadniveaus bijgewerkt voor 18 SKUs',
    uitgevoerdOp: '2024-06-04T09:31:00Z',
  },
  {
    id: 'SYNC-007',
    kanaal: 'Mirakl',
    type: 'voorraad',
    status: 'warning',
    aantalVerwerkt: 20,
    aantalFouten: 2,
    bericht: '2 SKUs konden niet worden bijgewerkt: product niet gevonden op Mirakl',
    uitgevoerdOp: '2024-06-04T09:32:00Z',
  },
  {
    id: 'SYNC-008',
    kanaal: 'eBay',
    type: 'voorraad',
    status: 'error',
    aantalVerwerkt: 0,
    aantalFouten: 10,
    bericht: 'Synchronisatie gestopt: API-limiet bereikt',
    uitgevoerdOp: '2024-06-04T09:33:00Z',
  },
  {
    id: 'SYNC-009',
    kanaal: 'WooCommerce',
    type: 'producten',
    status: 'success',
    aantalVerwerkt: 24,
    aantalFouten: 0,
    bericht: 'Productgegevens gesynchroniseerd',
    uitgevoerdOp: '2024-06-04T08:00:00Z',
  },
  {
    id: 'SYNC-010',
    kanaal: 'bol.com',
    type: 'producten',
    status: 'success',
    aantalVerwerkt: 16,
    aantalFouten: 0,
    bericht: 'Productgegevens gesynchroniseerd',
    uitgevoerdOp: '2024-06-04T08:01:00Z',
  },
  {
    id: 'SYNC-011',
    kanaal: 'WooCommerce',
    type: 'orders',
    status: 'success',
    aantalVerwerkt: 6,
    aantalFouten: 0,
    bericht: 'Alle orders succesvol gesynchroniseerd',
    uitgevoerdOp: '2024-06-03T10:00:00Z',
  },
  {
    id: 'SYNC-012',
    kanaal: 'Mirakl',
    type: 'orders',
    status: 'success',
    aantalVerwerkt: 3,
    aantalFouten: 0,
    bericht: 'Alle orders succesvol gesynchroniseerd',
    uitgevoerdOp: '2024-06-03T10:02:00Z',
  },
  {
    id: 'SYNC-013',
    kanaal: 'eBay',
    type: 'orders',
    status: 'warning',
    aantalVerwerkt: 2,
    aantalFouten: 1,
    bericht: '1 order overgeslagen: dubbel ordernummer gedetecteerd',
    uitgevoerdOp: '2024-06-03T10:03:00Z',
  },
  {
    id: 'SYNC-014',
    kanaal: 'bol.com',
    type: 'voorraad',
    status: 'success',
    aantalVerwerkt: 18,
    aantalFouten: 0,
    bericht: 'Voorraadniveaus bijgewerkt',
    uitgevoerdOp: '2024-06-03T09:30:00Z',
  },
  {
    id: 'SYNC-015',
    kanaal: 'Mirakl',
    type: 'producten',
    status: 'warning',
    aantalVerwerkt: 10,
    aantalFouten: 3,
    bericht: '3 producten afgewezen door Mirakl: ontbrekende EAN-code',
    uitgevoerdOp: '2024-06-03T08:05:00Z',
  },
]
